### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJModels.jl#100]
Would be nice to  port  the contrib.md from MLJ with a  few specificities (e.g. style; how to test etc). 

I can suggest a draft for this eventually.

**Comment by davidbp** [comment]
Good idea!

I would like to propose to use a set of  "common variable names" that should facilitate reading across different MLJModel algorithms

- `n_examples` or `n_observations`: number of examples/observations (should be allways an int >=1)
    - I would avoid `n_samples` or  `samples` specially if we end up having models that can generate generate samples !

- `n_features`: number of elements in a feature vector

- `X`: Array/Table/DataFrame containing `n_examples`

- `y`: CategoricalArray or Array containing `n_examples`

**Comment by tlienart** [comment]
Hey yes that's great (and good that you bumped up this issue, clearly I did not do what I was supposed to...)

With respect to the proposals, I think there's generally a bit of an organic consensus for the following; I added a _check_ where it's unclear whether it's used throughout 

* `X` a table object with `n` rows and `p` columns
* `Xmatrix` a matrix object obtained with `MLJBase.matrix(X)` possibly transposed but with appropriate dimension for the model 
* `y` an AbstractVector with `n` rows or a table object with `n` rows and `c` columns (multi-target); 
* `yplain` in classification, a vector of UInt `1,..., nclasses`
* (_check_) `c` number of targets
* `n` number of records, always, I'm pretty strongly opposed to using `n` for anything else and also to have other names for the number of records as there's basically a convention in the literature `n x p` (usually in ML) vs `p x n` (sometimes in stats) and everyone kind of knows what that means; so I'm against suggestions to call it `n_examples` etc
* `p` number of features, always, similar message
* `nclasses` number of classes
* `Xnew` a table object passed to `predict` or `transform`, with `p` columns

Then there's a number of things with some flexibility which should ideally be streamlined to help out, particularly around how the fitresults are passed; in the regression case it's usually fairly straightforward, but in the classification case, fitresult often ends up being a tuple of multiple sub things containing for instance `y[1]` to keep track of the classes. 

There's also some streamlining that could be done in terms of where/how the algorithms are described; some of this has been streamlined in MultivariateStats with @OkonSamuel and in NearestNeighbors but I haven't yet done that everywhere, but my recommendation would be to kind of follow these examples

**Comment by davidbp** [comment]
Where did you extract your notation? could you tell provide a source?

Let me write the notation of a textbook that I like:

#### Pattern recognition and machine learning (C. Bishop)

- `N` Number of elements in the dataset
- `n` index of a particular example in the dataset ($x_n$ is the n'th example, they always use letters in bold if examples are vectors $\bf{x}_n$ )
- `M` number of features (length of $\bf{x}$)

Some other comments:


#### Coherent use of capitals, CammelCase/snake_case across the codebase.

Some rules we could follow:

- Types/abstract types should be written using CamelCase.

- Functions should be written using snake_case.

- Variable names should follow snake_case notation. 
    - Example: `n_classes` instead of `nclasses`.

- Arrays of dimension bigger than 2 should start with a capital character. 
    - Example: `Xtrain` or `X_train` instead of `xtrain` or `x_train`.

- The previous rule should apply to all letters with the exception of some special characters that could be saved for indexing. 
    - Example: `N` and `M` that could be used as upper bounds of indices 
    - Personal taste: I like the idea to lowercase letters for indices of capital letters to refer to the maximum number allowed by an index: `n` for index up to `N` (as it is done in Bishop's book)


#### Unicode debate notation 

- Should we use Unicode characters at all? 
    - ϵ or `epsilon` ?

In almost all ML books there is the convention to use bold letters to matrices.

Usually, capital letters refer to "tensor/matrices" and lowercase letters refer to "vectors". 

In Julia we could do  `\bfw + tab`  to write $\bf{w}$. This would make the comparison between pseudocode and real code quite easy but is not standard at all. In the programming world, Unicode characters are sometimes seen as a "heretical sin". I think using this notation in the codebase should also facilitate reading


- 𝐗 = rand(100,10)    # some dataset
- 𝐱 = 𝐗[1]            # training example
- 𝐱 = rand(10)         # vector

**Comment by tlienart** [comment]
> Where did you extract your notation? could you tell provide a source?
> I should add I do not wish to discuss over notation too much. I would like to have a guideline soon in order to keep my code consistent with the codebase from MLJModels. In any case, whatever notation you decide, I would like to have some coherent use of capitals, CammelCase, snakecase etc...

Makes sense, so it's `n x p` the convention, please use that. We could waste time finding articles that do and articles that don't use it but it's not super useful. The fundamentals are the same: rows=records, columns=features (as opposed to, e.g., the conventions in JuliaStats).

> Some other comments:
> #### Coherent use of capitals, CammelCase/snake_case across the codebase.
> 
> Some rules we could follow:

I believe these rules are basically  from the Julia style (i.e. what they use in Base) and yes the hope is to use that. But to summarise

- types - CamelCase
- functions - snake case, adding underline whenever the compact form is not readable, so `confusion_matrix` but `truepositive` and `nclasses`
- variable names as function names
- yes for capital character for tables (`Xtrain`, `Xmatrix`) 

> #### Unicode debate notation
> 
>     * Should we use Unicode characters at all?
>       
>       * ϵ or `epsilon` ?

if I'm not mistaken we don't use a lot of unicode; but they're tolerated. The one thing we try not to do is use lower case and upper case indices as they sometimes render poorly / are not super readable so things like `x\_1` prefer `x_1`, basically follow a tradeoff between concision and readability. 

> In almost all ML books there is the convention to use bold letters to matrices.

we will not do  that

### Other stuff

at the moment there's a bit of inconsistency around how we place the arguments and kwargs of functions which we should harmonise (-> follow Julia style), also stuff like spacing before/after commas (yes: `a, b`), whether to  use a return (yes, always apart from one-line functions), etc.

Thanks for your input in any case! I'll try to come up  with something either today or within the next few days that we can use. I'll probably base myself from one of the existing style recommendations like the one from Invenia

**Comment by tlienart** [comment]
the README now has better guidelines for how to write an interface to MLJ; we should have a style guide as well but that would be better in MLJ itself. I'll close the issue here though feedback is welcome for the  new readme.
