### ISSUE TITLE
some package names are unknown when running @update

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJModels.jl#104]
some packages not found after running 
``` julia
using MLJModels
@update
```
`[ Info: Packages to be searched for model implementations:
NearestNeighbors
ScikitLearn
ScientificTypes
NaiveBayes
MultivariateStats
DecisionTree
Clustering
XGBoost
MLJModels
LIBSVM
GLM
Activating environment at `C:\Users\okons\ClonedRepos\MLJModels.jl\src\registry\Project.toml`
[ Info: resolving registry environment...
 Resolving package versions...
  Updating `C:\Users\okons\ClonedRepos\MLJModels.jl\src\registry\Project.toml`
 [no changes]
  Updating `C:\Users\okons\ClonedRepos\MLJModels.jl\src\registry\Manifest.toml`
 [no changes]
[ Info: Instantiating registry environment...
  Updating registry at `C:\Users\okons\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
[ Info: Loading registered packages...
[ Info: Generating model metadata...
DeterministicConstantClassifier✗ (package_name is :unknown)
DeterministicConstantRegressor✗ (package_name is :unknown)
MLJModels.DecisionTree_.DecisionTreeRegressor✔ 
MLJModels.LIBSVM_.EpsilonSVR✔ 
MLJModels.LIBSVM_.LinearSVC✔ 
MLJModels.LIBSVM_.NuSVC✔ 
MLJModels.LIBSVM_.NuSVR✔ 
MLJModels.LIBSVM_.SVC✔ 
MLJModels.MultivariateStats_.RidgeRegressor✔ 
MLJModels.NearestNeighbors_.KNNRegressor✔ 
MLJModels.ScikitLearn_.ARDRegressor✔ 
MLJModels.ScikitLearn_.AdaBoostRegressor✔ 
MLJModels.ScikitLearn_.BaggingRegressor✔ 
MLJModels.ScikitLearn_.BayesianRidgeRegressor✔ 
MLJModels.ScikitLearn_.DummyRegressor✔ 
MLJModels.ScikitLearn_.ElasticNetCVRegressor✔ 
MLJModels.ScikitLearn_.ElasticNetRegressor✔ 
MLJModels.ScikitLearn_.ExtraTreesRegressor✔ 
MLJModels.ScikitLearn_.GaussianProcessRegressor✔ 
MLJModels.ScikitLearn_.GradientBoostingRegressor✔ 
MLJModels.ScikitLearn_.HuberRegressor✔ 
MLJModels.ScikitLearn_.KNeighborsRegressor✔ 
MLJModels.ScikitLearn_.LarsCVRegressor✔ 
MLJModels.ScikitLearn_.LarsRegressor✔ 
MLJModels.ScikitLearn_.LassoCVRegressor✔ 
MLJModels.ScikitLearn_.LassoLarsCVRegressor✔ 
MLJModels.ScikitLearn_.LassoLarsICRegressor✔ 
MLJModels.ScikitLearn_.LassoLarsRegressor✔ 
MLJModels.ScikitLearn_.LassoRegressor✔ 
MLJModels.ScikitLearn_.LinearRegressor✔ 
MLJModels.ScikitLearn_.MultiTaskElasticNetCVRegressor✔ 
MLJModels.ScikitLearn_.MultiTaskElasticNetRegressor✔ 
MLJModels.ScikitLearn_.MultiTaskLassoCVRegressor✔ 
MLJModels.ScikitLearn_.MultiTaskLassoRegressor✔ 
MLJModels.ScikitLearn_.OrthogonalMatchingPursuitCVRegressor✔ 
MLJModels.ScikitLearn_.OrthogonalMatchingPursuitRegressor✔ 
MLJModels.ScikitLearn_.PassiveAggressiveClassifier✔ 
MLJModels.ScikitLearn_.PassiveAggressiveRegressor✔ 
MLJModels.ScikitLearn_.PerceptronClassifier✔ 
MLJModels.ScikitLearn_.RANSACRegressor✔ 
MLJModels.ScikitLearn_.RandomForestRegressor✔ 
MLJModels.ScikitLearn_.RidgeCVClassifier✔ 
MLJModels.ScikitLearn_.RidgeCVRegressor✔ 
MLJModels.ScikitLearn_.RidgeClassifier✔ 
MLJModels.ScikitLearn_.RidgeRegressor✔ 
MLJModels.ScikitLearn_.SGDClassifier✔ 
MLJModels.ScikitLearn_.SGDRegressor✔ 
MLJModels.ScikitLearn_.SVMClassifier✔ 
MLJModels.ScikitLearn_.SVMLClassifier✔ 
MLJModels.ScikitLearn_.SVMLRegressor✔ 
MLJModels.ScikitLearn_.SVMNuClassifier✔ 
MLJModels.ScikitLearn_.SVMNuRegressor✔ 
MLJModels.ScikitLearn_.SVMRegressor✔ 
MLJModels.ScikitLearn_.TheilSenRegressor✔ 
MLJModels.XGBoost_.XGBoostCount✔ 
MLJModels.XGBoost_.XGBoostRegressor✔ 
ConstantClassifier✗ (package_name is :unknown)
ConstantRegressor✗ (package_name is :unknown)
MLJModels.DecisionTree_.DecisionTreeClassifier✔ 
MLJModels.GLM_.LinearBinaryClassifier✔ 
MLJModels.GLM_.LinearCountRegressor✔ 
MLJModels.GLM_.LinearRegressor✔ 
MLJModels.MultivariateStats_.LDA✔ 
MLJModels.NaiveBayes_.GaussianNBClassifier✔ 
MLJModels.NaiveBayes_.MultinomialNBClassifier✔ 
MLJModels.NearestNeighbors_.KNNClassifier✔ 
MLJModels.ScikitLearn_.AdaBoostClassifier✔ 
MLJModels.ScikitLearn_.BaggingClassifier✔ 
MLJModels.ScikitLearn_.BernoulliNBClassifier✔ 
MLJModels.ScikitLearn_.ComplementNBClassifier✔ 
MLJModels.ScikitLearn_.DummyClassifier✔ 
MLJModels.ScikitLearn_.ExtraTreesClassifier✔ 
MLJModels.ScikitLearn_.GaussianNBClassifier✔ 
MLJModels.ScikitLearn_.GaussianProcessClassifier✔ 
MLJModels.ScikitLearn_.GradientBoostingClassifier✔ 
MLJModels.ScikitLearn_.KNeighborsClassifier✔ 
MLJModels.ScikitLearn_.LogisticCVClassifier✔ 
MLJModels.ScikitLearn_.LogisticClassifier✔ 
MLJModels.ScikitLearn_.MultinomialNBClassifier✔ 
MLJModels.ScikitLearn_.ProbabilisticSGDClassifier✔ 
MLJModels.ScikitLearn_.RandomForestClassifier✔ 
MLJModels.XGBoost_.XGBoostClassifier✔ 
FeatureSelector✗ (package_name is :unknown)
FillImputer✗ (package_name is :unknown)
MLJModels.Clustering_.KMeans✔ 
MLJModels.Clustering_.KMedoids✔ 
MLJModels.LIBSVM_.OneClassSVM✔ 
MLJModels.MultivariateStats_.ICA✔ 
MLJModels.MultivariateStats_.KernelPCA✔ 
MLJModels.MultivariateStats_.PCA✔ 
OneHotEncoder✗ (package_name is :unknown)
Standardizer✗ (package_name is :unknown)
StaticTransformer✗ (package_name is :unknown)
UnivariateBoxCoxTransformer✗ (package_name is :unknown)
UnivariateDiscretizer✗ (package_name is :unknown)
UnivariateStandardizer✗ (package_name is :unknown)
If you have called @update from the REPL then your namespace is now polluted. Restart your REPL. 
true`

**Comment by tlienart** [comment]
Please do not do the update, we'll do it, thanks!
