### ISSUE TITLE
Can a supervised model also implement the transform method.

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJModels.jl#117]
Can a supervised model also implement the transform method or is it restricted to unsupervised models only.

**Comment by ablaom** [comment]
Yes, it can! 

Curious about the use case.

In MLJFlux we are working on neural nets that learn feature embeddings along with the main layers. The `transform` method maps the categorical features into their learned embeddings for use in other models that only handle continuous data.

**Comment by OkonSamuel** [comment]
Oh I just thought  may want to use lda to reduce the dimension of a dataset before applying another classification model

**Comment by tlienart** [comment]
right so you want to have a `transform` that uses the projection matrix learned in the LDA? I think you can "just" do that by defining a `MLJBase.transform(::BayesianLDA ... )`

**Comment by ablaom** [comment]
You should also declare an `output_scitype`. Currently this is not reported in the registry unless the model is unsupervised, and I don't think this is used. However, for future proofing, it would be good to have. So, you probably want something like:

```julia
using ScientificTypes
MLJBase.output_scitype(::Type{<:BayesianLDA}) = Table(Continuous)
```

This is assuming you convert your transformed inputs into tabular form (the recommendation for consistency with PCA, and so forth), which you do with `MLJBase.table(Xreduced)`. This automatically adds labels to the columns (`x1, x2, `etc I think).
