### ISSUE TITLE
DecisionTree doesn't handle multiclass input?

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJModels.jl#134]
Their readme clearly states that it  handles  cateogircals yet the `input_scitype` is marked as Continuous and it indeed seems that it does not in fact handle categoricals because it needs to  be able to define a `isless` operation?

Opening an issue on DecisionTree as well for clarifications: https://github.com/bensadeghi/DecisionTree.jl/issues/92

**Comment by ablaom** [comment]
I think this has now been clarified at the above thread. The DecisionTree `input_scitype`s could be updated to `Table(Continuous, OrderedFactor, Count)` but with a comment in the doc-string that coercion of `OrderedFactor` columns to `Count` or `Continuous` may lead to better performance, without affecting outcomes.

**Comment by ablaom** [comment]
To be clear, `Multiclass` is not strictly supported. If such data is coerced to one of the other ordered types, declaring  what the order should be, then the outcome of training will depend on that order.
