### ISSUE TITLE
Add multivariatestats as hard dep

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJModels.jl#135]
For a reason I don't understand, the  fact that MultivariateStats is not a hard dep  seems to annoy MLJModels which results in annoying warnings etc.

Best is probably to  cave in and just add the thing for now. It takes 0.5s to load so probably fine.

**Comment by ablaom** [comment]
Yes I have experienced this, although not consistently. Happy for this to proceed.
