### ISSUE TITLE
Parameter name convention

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJModels.jl#138]
This may be a  bit tricky but some pain points below:

* Sklearn calls its default hp `alpha` in MLJLM they're called `lambda`
* KNN models take a `K=` whereas kmeans takes a `k=`

I imagine there's more of those.

This may require the super boring-yet-maybe-necessary list of how to write parameters / conventions

**Comment by ablaom** [comment]
Perhaps I misunderstand. Are you saying the MLJ interfaces should attempt to "coerce" similar models in different packages to adhere to a common hyper parameter naming convention? I think this is unrealistic. I think the names in the MLJ interface should always match the names used in the external  package (and appearing in their documentation, which we do not want to duplicate). I believe this policy has been a consistently applied policy, so far. 

In the case of KNNRegressor, which you wrote, I wickedly reverted your choice to the one in the old KNNRegressor, to prevent breaking tonnes of code. KNNRegressor is used ubiquitously in testing. Happy for you to tackle the refactoring, if you think it's important.

**Comment by tlienart** [comment]
What you're saying makes sense, but I can imagine it being a pain point, though there's not much we can do about it and your suggestion seems more reasonable in terms of how much maintenance we have to  do
