### ISSUE TITLE
One-encoder should (optionally) coerce Count data to Continuous

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJModels.jl#153]
Motivated by the experiences of a user [here](https://github.com/alan-turing-institute/MLJ.jl/issues/376) I suggest we do this. 

Instead of this:

```julia
julia> OneHotEncoder()
OneHotEncoder(features = Symbol[],
              drop_last = false,
              ordered_factor = true,)
```

we could have this

```julia
julia> OneHotEncoder()
OneHotEncoder(features = Symbol[],
              drop_last = false,
              ordered_factor = true,
              count = true)
```

Any objections?

**Comment by tlienart** [comment]
This seems weird to me, the coercion has nothing to do with OHE? 

But I don't really care much though I'd prefer if it were called  `coerce_count` and `false` by default.

Also probably this should wait until https://github.com/alan-turing-institute/ScientificTypes.jl/pull/63 is merged with the syntax  `Count => Continuous`.

**Comment by ablaom** [comment]
@tlienart Yeah, on reflection, it is a bit weird. And in view of ST issue 63, kind of unnecessary.
