### ISSUE TITLE
Add `importance` in  XGBoost report

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJModels.jl#163]

**Comment by ablaom** [comment]
As far as I can tell this is not straightforward, as the feature importances do not appear accessible through the  XGBoost.jl wrapper MLJ uses.

**Comment by ablaom** [comment]
Yes, fortunatley I am wrong: https://github.com/dmlc/XGBoost.jl/issues/81#issuecomment-573548332
