### ISSUE TITLE
Reset default regcoef parameter in LDA.

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJModels.jl#181]
By default the `regcoef`parameter in `LDA` and  `BayesianLDA` models from `MultivariateStats` package is set to `0`. This poses two issues
1. It throws a `PosDefException` error when fitting with the `:gsvd` method which can be confusing to users not too familiar with the model.
2. Although there are no errors when fitting with the `:whiten` method. It produces an error when the `predict` method is called.

I suggest resetting the default `regcoef` parameter to `1e-6` if using the Standard Covariance Estimator and setting to zero if using other Covariance Estimator.
@tlienart what's your opinion

**Comment by tlienart** [comment]
Sounds good, are you happy to suggest a PR for this? thanks  a lot!
