### ISSUE TITLE
Remove RDatasets from [extras]

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJModels.jl#218]
In view of the increasing challenges (eg, #159 #217 ) of managing the [extras] packages, for which we cannot specify compatibility constraints, let's remove this dependency, using the built-in test sets from MLJBase instead. 

GLM tests currently use a melanoma test set for logistic regression, but `crabs` should do for this, I expect. 

For the record the built-in sets are these:

```julia
@load_ames         @load_boston        @load_crabs         @load_iris          @load_reduced_ames
```

We can also use any data set from OpenML, using `OpenML.load(id)`, but I don't see that we should need to.

**Comment by OkonSamuel** [comment]
@ablaom some  MultivariateStats tests also depends on Rdatasets

**Comment by ablaom** [comment]
Yes and possibly others too. I haven't grepped the code yet.
