### ISSUE TITLE
[register new model] ParallelKMeans.jl

### ISSUE THREAD

**Issue by PyDataBlog** [alan-turing-institute/MLJModels.jl#226]
Hi

After following the guidelines for exposing our package to the MLJ API, we would like to propose for the merging of the package in question.

Here's a direct link for the[ interface code](https://github.com/PyDataBlog/ParallelKMeans.jl/blob/master/src/mlj_interface.jl). We are open to any edits required to conform to the MLJ API.

**Comment by tlienart** [comment]
I'll let @ablaom also have a look but I think it's good to go, we just need to run the usual machinery with the registry and your model will be in the mix :)

**Comment by PyDataBlog** [comment]
@tlienart @ablaom even better news.  We have just been updated with new algorithms and the MLJ interface even cleaner and more robust now.

**Comment by ablaom** [comment]
Looks great. Couple of observations/comments:

- your `fit` method appears to be missing the `verbosity` argument. So the signature is `fit(model, verbosity::Integer, X)`. You don't need to use the verbosity, but if you want,  `0` is warnings only, and `<= 0` is silent, and `>=1` for verbose logging. Your tests may not have caught this b/s of some legacy code that might disappear.

- You have specified the output scitype as `Table(Count)`. Why `Count` and not `Continuous`? The `output_scitype` trait records the scientific type of what your `transform` outputs.

**Comment by PyDataBlog** [comment]
@ablaom we will make these new changes in a patch release today.

Also, won't `Continous` make outputs floats instead of integers?

**Comment by tlienart** [comment]
There's a distinction between *transform* and *predict*, the former returns a transformed view of whatever data you have, in the case of classical KMeans the transform are the vectors linking points to their centroids.

The "prediction" corresponds to the label of the cluster, this won't be affected. 

Have a look at the metadata for Clustering/KMeans it should clarify things

**Comment by PyDataBlog** [comment]
@tlienart @ablaom all the issues raised have been fixed in the latest`0.1.3` now.

**Comment by ablaom** [comment]
@PyDataBlog Thanks for that.

Okay, there still seems to be confusion about @tlienart 's comment. 

 - `transform` is the projection operator defined by the clustering, and so outputs a table of floats, one column per centroid. It still looks to me like your outputting class labels 

- ` predict` outputs the class labels, which should be a  `CategoricalVector` (not a plain vector of integers)

Here's the Clustering.jl model in action demonstrating the behaviour we are after here:

```julia
using MLJ, MLJBase
model = @load KMeans pkg=Clustering
X = MLJ.table(rand(1000, 10));

@assert scitype(X) <: Table(Continuous)
fitresult, _, _ = MLJBase.fit(model, 0, X);

# the transform method projects onto smaller-dimensional space (in
# this case 3d):
Xnew = MLJ.table(rand(2, 10));
Xreduced = MLJBase.transform(model, fitresult, Xnew);

julia> pretty(Xreduced)
┌────────────────────┬────────────────────┬─────────────────────┐
│ x1                 │ x2                 │ x3                  │
│ Float64            │ Float64            │ Float64             │
│ Continuous         │ Continuous         │ Continuous          │
├────────────────────┼────────────────────┼─────────────────────┤
│ 1.182453691310294  │ 0.6190599421094625 │ 1.0995128608846416  │
│ 0.8625052279332213 │ 0.7667887849423467 │ 0.40204753569099516 │
└────────────────────┴────────────────────┴─────────────────────┘

julia> scitype(Xreduced)
Table{AbstractArray{Continuous,1}}

julia> @assert scitype(Xreduced) <: Table(Continuous)

# the predict method outputs class labels, which will be a categorical
# vector (NOT a vector of raw integers):
julia> yhat = MLJBase.predict(model, fitresult, Xnew)
julia> yhat = MLJBase.predict(model, fitresult, Xnew)
2-element CategoricalArrays.CategoricalArray{Int64,1,UInt32}:
 2
 3

julia> scitype(yhat)
AbstractArray{Multiclass{3},1}

julia> @assert scitype(yhat) <: AbstractVector{<:Multiclass}

# In particular, yhat knows all the class labels!!
julia> levels(yhat)
3-element Array{Int64,1}:
 1
 2
 3
```

Your metadata reflects the scitype assertions shown above and should look like this:

```julia
MMI.metadata_model(KMeans,
    input   = MMI.Table(MMI.Continuous),           # scitype of input
    output  = MMI.Table(MMI.Continuous),          # scitype of transformations
    target =  AbstractArray{<:Multiclass}             # scitype of predictions
    weights = false,
    descr   = ParallelKMeans_Desc,
    path	= "ParallelKMeans.KMeans")
```

Is this clearer?

**Comment by PyDataBlog** [comment]
Clearer now. The necessary changes will be made and released.

**Comment by PyDataBlog** [comment]
@ablaom we have updated based on all the examples now in `v0.1.4`. Hopefully, it fixes all the raised issues.

**Comment by ablaom** [comment]
Have reviewed the changes. all good! working on a new MLJModels release with the updated registry. should be done within 24 hours

**Comment by ablaom** [comment]
All done 🎉 

@PyDataBlog Final steps:

- Wait for https://github.com/JuliaRegistries/General/pull/13385 to merge

- Update your local MLJModels version to 0.9.6

- Test the code below works

- Close this issue to confirm 

```
using MLJ

X, y = @load_iris;
model = @load KMeans pkg=ParallelKMeans
mach = fit!(machine(model, X))

# transforming:
Xsmall = transform(mach);
selectrows(Xsmall, 1:4) |> pretty

# predicting:
yhat = predict(mach);
compare = zip(yhat, y) |> collect;
compare[1:8]
compare[51:58]
compare[101:108]
```

**Comment by PyDataBlog** [comment]
@ablaom thanks for your patience, time and dedication. Everything works like a charm! Closing issue.
