### ISSUE TITLE
Improve convenience for loading models with duplicate names

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJModels.jl#242]
Context: 
- [ ] https://github.com/alan-turing-institute/MLJ.jl/issues/446
- [ ] https://github.com/alan-turing-institute/MLJ.jl/issues/257

**Comment by ablaom** [comment]
While we're here, check if something can be done about #243, although I suspect "disintegration" of MLJModels will be the ultimate solution.

**Comment by OkonSamuel** [comment]
Something in the lines of 
```julia
@load LinearRegressor pkg=package name=ModelName
```
or 
```julia
@load LinearRegressor as ModelName pkg=package name=ModelName
```
might be helpful when the same model types are imported in a given module from different packages.

Note
In the first case the `name` keyword is optional. The user would tend to use it when he tries to import a model type that's already present and he sees the following error `ERROR: invalid redefinition of type`(This is julia's normal behaviour by the way)

**Comment by ablaom** [comment]
In fact, the *function* `load` already has an option `allow_amibiguous` and the behaviour, when set to `true` is this: When a duplicate is loaded, the old struct is still accessible by the unqualified name, but the new struct must be qualified:

```julia
julia> model1 = load("RidgeRegressor", pkg="MLJLinearModels",
       allow_ambiguous = true)

julia> RidgeRegressor
RidgeRegressor

julia> model1 = load("RidgeRegressor", pkg="MultivariateStats",
       allow_ambiguous = true)
WARNING: ignoring conflicting import of MultivariateStats_.RidgeRegressor into Main

julia> info(RidgeRegressor).package_name
"MLJLinearModels"

julia> info(MLJModels.MultivariateStats_.RidgeRegressor).package_name
"MultivariateStats"
```
