### ISSUE TITLE
Tests failing on MacOS

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJModels.jl#256]
```
INTEL MKL ERROR: dlopen(/Users/travis/.julia/conda/3/lib/libmkl_intel_thread.dylib, 9): Library not loaded: @rpath/libiomp5.dylib

  Referenced from: /Users/travis/.julia/conda/3/lib/libmkl_intel_thread.dylib

  Reason: image not found.

Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib
```
https://travis-ci.com/github/alan-turing-institute/MLJModels.jl/jobs/339809727#L470
PS
 Just ran tests again using the current master from forked repo (Same as present master) and the MacOS tests still fails. @tlienart  @ablaom if you use a Mac could you check

**Comment by ablaom** [comment]
I get a pass using Julia 1.0 on my mac but my installation is using different python installation and I don't know how to change this. 

For what it is worth, here is the conda install for this failing build:

```
 package                    |            build
451    ---------------------------|-----------------
452    joblib-0.15.1              |             py_0         208 KB
453    llvm-openmp-10.0.0         |       h28b9765_0         236 KB
454    scikit-learn-0.22.1        |   py37h27c97d8_0         4.7 MB
455    scipy-1.4.1                |   py37h9fa6033_0        12.9 MB
456    ------------------------------------------------------------
457                                           Total:        18.0 MB
```

And here's the latest build on master that passed:

```
package                    |            build
429    ---------------------------|-----------------
430    joblib-0.14.1              |             py_0         201 KB
431    llvm-openmp-4.0.1          |       hcfea43d_1         409 KB
432    scikit-learn-0.22.1        |   py37h27c97d8_0         4.7 MB
433    scipy-1.4.1                |   py37h9fa6033_0        12.9 MB
434    ------------------------------------------------------------
435                                           Total:        18.1 MB
436
437
```

The scikit-learn versions are the same but there is a substantial change in llvm-opemp (from 4 to 10).

**Comment by OkonSamuel** [comment]
To change PYCall's python use `ENV["PYTHON"]=Conda`

**Comment by ablaom** [comment]
Thanks for that. However, if I do wither of these tests still pass. But I'm not convinced this actually changes the version of scikit-learn that is used. After resetting the ENV and doing a `build`, I have this:

```
(py37) humus:pkgs anthony$ ls /Users/anthony/.julia/conda/3/pkgs/scikit*
/Users/anthony/.julia/conda/3/pkgs/scikit-learn-0.21.3-py37h27c97d8_0.conda
```
Isn't that the version that's being used. That's an older version of scikitlearn. 

(And how do I get `test` to explicitly report the versions installed, as in the CI? I never get that logging in my local testing.)

**Comment by tlienart** [comment]
can we just ignore tests on OSX? travis seems to be doing a shitty job and stuff works fine locally... it's  a bit overkill to test both linux and osx, it makes sense for binaries like xgboost and lightgbm but these are tested in  their local packages so 🤷‍♂️

**Comment by OkonSamuel** [comment]
Did some research and found that [this](https://docs.anaconda.com/mkl-optimizations/) is probably the cause.
It might also be one of the causes of previous test failing on MacOS in 1.3

**Comment by ablaom** [comment]
@azev77 I wonder if you could test the remedy for MKL errors suggested at @OkonSamuel 's link, more precisely [here](https://docs.anaconda.com/mkl-optimizations/#uninstalling-mkl)?

**Comment by ablaom** [comment]
This non-MLJ issue is known and we are tracking it, so closing.
