### ISSUE TITLE
ScikitLearn and versions

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJModels.jl#260]
Consider:

<img width="419" alt="Screen Shot 2020-05-28 at 16 56 10" src="https://user-images.githubusercontent.com/10897531/83157676-2d4a3300-a104-11ea-9336-654cf819a0ac.png">

and

<img width="578" alt="Screen Shot 2020-05-28 at 16 56 43" src="https://user-images.githubusercontent.com/10897531/83157757-3fc46c80-a104-11ea-8cb7-28d12fcec616.png">

what the hell? I might understand a few of those but decreasing **patch  versions** ?? also how can a package have  so much impact?

**Comment by tlienart** [comment]
Fingers crossed this goes away when we move to MLJScikit

**Comment by OkonSamuel** [comment]
> Fingers crossed this goes away when we move to MLJScikit

This should help reduce the chances of this happening. It is worth noting that i don't experience this with **ScikitLearn v0.6.2**. Please confirm this.

<pre><font color="#839496"><b>(@v1.4) pkg&gt; </b></font>st
<font color="#586E75"><b>Status</b></font> `~/.julia/environments/v1.4/Project.toml`
 <font color="#002B36"> [6e4b80f9]</font><font color="#EEE8D5"> BenchmarkTools v0.5.0</font>
 <font color="#002B36"> [336ed68f]</font><font color="#EEE8D5"> CSV v0.6.2</font>
 <font color="#002B36"> [324d7699]</font><font color="#EEE8D5"> CategoricalArrays v0.8.1</font>
 <font color="#002B36"> [aaaa29a8]</font><font color="#EEE8D5"> Clustering v0.14.0</font>
 <font color="#002B36"> [861a8166]</font><font color="#EEE8D5"> Combinatorics v1.0.2</font>
 <font color="#002B36"> [ed09eef8]</font><font color="#EEE8D5"> ComputationalResources v0.3.2</font>
 <font color="#002B36"> [8f4d0f93]</font><font color="#EEE8D5"> Conda v1.4.1</font>
 <font color="#002B36"> [d58978e5]</font><font color="#EEE8D5"> Dagger v0.8.0</font>
 <font color="#002B36"> [a93c6f00]</font><font color="#EEE8D5"> DataFrames v0.21.2</font>
 <font color="#002B36"> [7806a523]</font><font color="#EEE8D5"> DecisionTree v0.10.3</font>
 <font color="#002B36"> [b4f34e82]</font><font color="#EEE8D5"> Distances v0.8.2</font>
 <font color="#002B36"> [31c24e10]</font><font color="#EEE8D5"> Distributions v0.23.4</font>
 <font color="#002B36"> [e30172f5]</font><font color="#EEE8D5"> Documenter v0.24.11</font>
 <font color="#002B36"> [f6006082]</font><font color="#EEE8D5"> EvoTrees v0.3.0</font>
 <font color="#002B36"> [38e38edf]</font><font color="#EEE8D5"> GLM v1.3.9</font>
 <font color="#002B36"> [cc18c42c]</font><font color="#EEE8D5"> GaussianMixtures v0.3.1</font>
 <font color="#002B36"> [891a1506]</font><font color="#EEE8D5"> GaussianProcesses v0.12.1</font>
 <font color="#002B36"> [cd3eb016]</font><font color="#EEE8D5"> HTTP v0.8.15</font>
 <font color="#002B36"> [7073ff75]</font><font color="#EEE8D5"> IJulia v1.21.2</font>
 <font color="#002B36"> [6deec6e2]</font><font color="#EEE8D5"> IndexedTables v0.13.0</font>
 <font color="#002B36"> [4138dd39]</font><font color="#EEE8D5"> JLD v0.10.0</font>
 <font color="#002B36"> [b1bec4e5]</font><font color="#EEE8D5"> LIBSVM v0.4.0</font>
 <font color="#002B36"> [30fc2ffe]</font><font color="#EEE8D5"> LossFunctions v0.6.2</font>
 <font color="#002B36"> [add582a8]</font><font color="#EEE8D5"> MLJ v0.11.5</font>
 <font color="#002B36"> [a7f614a8]</font><font color="#EEE8D5"> MLJBase v0.13.10</font>
 <font color="#002B36"> [6ee0df7b]</font><font color="#EEE8D5"> MLJLinearModels v0.5.0</font>
 <font color="#002B36"> [2e2323e0]</font><font color="#EEE8D5"> MLJScientificTypes v0.2.7</font>
 <font color="#002B36"> [03970b2e]</font><font color="#EEE8D5"> MLJTuning v0.3.6</font>
 <font color="#002B36"> [6f286f6a]</font><font color="#EEE8D5"> MultivariateStats v0.7.0</font>
 <font color="#002B36"> [b8a86587]</font><font color="#EEE8D5"> NearestNeighbors v0.4.4</font>
 <font color="#002B36"> [42b8e9d4]</font><font color="#EEE8D5"> ParallelKMeans v0.1.8</font>
 <font color="#002B36"> [91a5bcdd]</font><font color="#EEE8D5"> Plots v1.4.2</font>
 <font color="#002B36"> [92933f4c]</font><font color="#EEE8D5"> ProgressMeter v1.3.1</font>
 <font color="#002B36"> [438e738f]</font><font color="#EEE8D5"> PyCall v1.91.4</font>
 <font color="#002B36"> [de320387]</font><font color="#EEE8D5"> PyCallJLD v0.1.0</font>
 <font color="#002B36"> [d330b81b]</font><font color="#EEE8D5"> PyPlot v2.9.0</font>
 <font color="#002B36"> [1a8c2f83]</font><font color="#EEE8D5"> Query v0.12.2</font>
 <font color="#002B36"> [612083be]</font><font color="#EEE8D5"> Queryverse v0.6.1</font>
 <font color="#002B36"> [6f49c342]</font><font color="#EEE8D5"> RCall v0.13.7</font>
 <font color="#002B36"> [ce6b1742]</font><font color="#EEE8D5"> RDatasets v0.6.9</font>
 <font color="#002B36"> [321657f4]</font><font color="#EEE8D5"> ScientificTypes v0.8.0</font>
 <font color="#002B36"> [3646fa90]</font><font color="#EEE8D5"> ScikitLearn v0.6.2</font>
 <font color="#002B36"> [aa65fe97]</font><font color="#EEE8D5"> SnoopCompile v1.4.0</font>
 <font color="#002B36"> [2913bbd2]</font><font color="#EEE8D5"> StatsBase v0.33.0</font>
 <font color="#002B36"> [b189fb0b]</font><font color="#EEE8D5"> ThreadPools v1.1.0</font>
 <font color="#002B36"> [ac1d9e8a]</font><font color="#EEE8D5"> ThreadsX v0.1.2</font>
 <font color="#002B36"> [9d95f2ec]</font><font color="#EEE8D5"> TypedTables v1.2.0</font>
 <font color="#002B36"> [856ac37a]</font><font color="#EEE8D5"> UrlDownload v0.3.0</font>
 <font color="#002B36"> [81def892]</font><font color="#EEE8D5"> VersionParsing v1.2.0</font>
 <font color="#002B36"> [44d3d7a6]</font><font color="#EEE8D5"> Weave v0.10.2</font>
 <font color="#002B36"> [009559a3]</font><font color="#EEE8D5"> XGBoost v0.4.3</font>
 <font color="#002B36"> [9a3f8284]</font><font color="#EEE8D5"> Random </font>
</pre>

**Comment by tlienart** [comment]
Thanks @OkonSamuel , I think once we make the move from holding the scikitlearn interface from here to MLJScikitLearnInterface.jl It will be less of an issue

**Comment by ablaom** [comment]
> Thanks @OkonSamuel , I think once we make the move from holding the scikitlearn interface from here to MLJScikitLearnInterface.jl It will be less of an issue

This migration is all done, since MLJModels 0.10 : https://github.com/alan-turing-institute/MLJModels.jl/releases/tag/v0.10.0

**Comment by OkonSamuel** [comment]
just tested it again this time installing `MLJScikitLearnInterface` and it works
<pre><font color="#839496"><b>(@v1.4) pkg&gt; </b></font>st
<font color="#586E75"><b>Status</b></font> `~/.julia/environments/v1.4/Project.toml`
 <font color="#002B36"> [6e4b80f9]</font><font color="#EEE8D5"> BenchmarkTools v0.5.0</font>
 <font color="#002B36"> [336ed68f]</font><font color="#EEE8D5"> CSV v0.6.2</font>
 <font color="#002B36"> [324d7699]</font><font color="#EEE8D5"> CategoricalArrays v0.8.1</font>
 <font color="#002B36"> [aaaa29a8]</font><font color="#EEE8D5"> Clustering v0.14.0</font>
 <font color="#002B36"> [861a8166]</font><font color="#EEE8D5"> Combinatorics v1.0.2</font>
 <font color="#002B36"> [ed09eef8]</font><font color="#EEE8D5"> ComputationalResources v0.3.2</font>
 <font color="#002B36"> [8f4d0f93]</font><font color="#EEE8D5"> Conda v1.4.1</font>
 <font color="#002B36"> [d58978e5]</font><font color="#EEE8D5"> Dagger v0.8.0</font>
 <font color="#002B36"> [a93c6f00]</font><font color="#EEE8D5"> DataFrames v0.21.2</font>
 <font color="#002B36"> [7806a523]</font><font color="#EEE8D5"> DecisionTree v0.10.3</font>
 <font color="#002B36"> [b4f34e82]</font><font color="#EEE8D5"> Distances v0.8.2</font>
 <font color="#002B36"> [31c24e10]</font><font color="#EEE8D5"> Distributions v0.23.4</font>
 <font color="#002B36"> [e30172f5]</font><font color="#EEE8D5"> Documenter v0.24.11</font>
 <font color="#002B36"> [f6006082]</font><font color="#EEE8D5"> EvoTrees v0.3.0</font>
 <font color="#002B36"> [38e38edf]</font><font color="#EEE8D5"> GLM v1.3.9</font>
 <font color="#002B36"> [cc18c42c]</font><font color="#EEE8D5"> GaussianMixtures v0.3.1</font>
 <font color="#002B36"> [891a1506]</font><font color="#EEE8D5"> GaussianProcesses v0.12.1</font>
 <font color="#002B36"> [cd3eb016]</font><font color="#EEE8D5"> HTTP v0.8.15</font>
 <font color="#002B36"> [7073ff75]</font><font color="#EEE8D5"> IJulia v1.21.2</font>
 <font color="#002B36"> [6deec6e2]</font><font color="#EEE8D5"> IndexedTables v0.13.0</font>
 <font color="#002B36"> [c601a237]</font><font color="#EEE8D5"> Interact v0.10.3</font>
 <font color="#002B36"> [4138dd39]</font><font color="#EEE8D5"> JLD v0.10.0</font>
 <font color="#002B36"> [b1bec4e5]</font><font color="#EEE8D5"> LIBSVM v0.4.0</font>
 <font color="#002B36"> [30fc2ffe]</font><font color="#EEE8D5"> LossFunctions v0.6.2</font>
 <font color="#002B36"> [add582a8]</font><font color="#EEE8D5"> MLJ v0.11.5</font>
 <font color="#002B36"> [a7f614a8]</font><font color="#EEE8D5"> MLJBase v0.13.10</font>
 <font color="#002B36"> [6ee0df7b]</font><font color="#EEE8D5"> MLJLinearModels v0.5.0</font>
 <font color="#002B36"> [d491faf4]</font><font color="#EEE8D5"> MLJModels v0.10.0</font>
 <font color="#002B36"> [2e2323e0]</font><font color="#EEE8D5"> MLJScientificTypes v0.2.7</font>
 <font color="#002B36"> [5ae90465]</font><font color="#EEE8D5"> MLJScikitLearnInterface v0.1.4</font>
 <font color="#002B36"> [03970b2e]</font><font color="#EEE8D5"> MLJTuning v0.3.6</font>
 <font color="#002B36"> [6f286f6a]</font><font color="#EEE8D5"> MultivariateStats v0.7.0</font>
 <font color="#002B36"> [b8a86587]</font><font color="#EEE8D5"> NearestNeighbors v0.4.4</font>
 <font color="#002B36"> [42b8e9d4]</font><font color="#EEE8D5"> ParallelKMeans v0.1.8</font>
 <font color="#002B36"> [91a5bcdd]</font><font color="#EEE8D5"> Plots v1.4.2</font>
 <font color="#002B36"> [92933f4c]</font><font color="#EEE8D5"> ProgressMeter v1.3.1</font>
 <font color="#002B36"> [438e738f]</font><font color="#EEE8D5"> PyCall v1.91.4</font>
 <font color="#002B36"> [de320387]</font><font color="#EEE8D5"> PyCallJLD v0.1.0</font>
 <font color="#002B36"> [d330b81b]</font><font color="#EEE8D5"> PyPlot v2.9.0</font>
 <font color="#002B36"> [1a8c2f83]</font><font color="#EEE8D5"> Query v0.12.2</font>
 <font color="#002B36"> [612083be]</font><font color="#EEE8D5"> Queryverse v0.6.1</font>
 <font color="#002B36"> [6f49c342]</font><font color="#EEE8D5"> RCall v0.13.7</font>
 <font color="#002B36"> [ce6b1742]</font><font color="#EEE8D5"> RDatasets v0.6.9</font>
 <font color="#002B36"> [321657f4]</font><font color="#EEE8D5"> ScientificTypes v0.8.0</font>
 <font color="#002B36"> [3646fa90]</font><font color="#EEE8D5"> ScikitLearn v0.6.2</font>
 <font color="#002B36"> [aa65fe97]</font><font color="#EEE8D5"> SnoopCompile v1.4.0</font>
 <font color="#002B36"> [2913bbd2]</font><font color="#EEE8D5"> StatsBase v0.33.0</font>
 <font color="#002B36"> [bd369af6]</font><font color="#EEE8D5"> Tables v1.0.4</font>
 <font color="#002B36"> [b189fb0b]</font><font color="#EEE8D5"> ThreadPools v1.1.0</font>
 <font color="#002B36"> [ac1d9e8a]</font><font color="#EEE8D5"> ThreadsX v0.1.2</font>
 <font color="#002B36"> [9d95f2ec]</font><font color="#EEE8D5"> TypedTables v1.2.0</font>
 <font color="#002B36"> [856ac37a]</font><font color="#EEE8D5"> UrlDownload v0.3.0</font>
 <font color="#002B36"> [81def892]</font><font color="#EEE8D5"> VersionParsing v1.2.0</font>
 <font color="#002B36"> [44d3d7a6]</font><font color="#EEE8D5"> Weave v0.10.2</font>
 <font color="#002B36"> [009559a3]</font><font color="#EEE8D5"> XGBoost v0.4.3</font>
 <font color="#002B36"> [9a3f8284]</font><font color="#EEE8D5"> Rando</font></pre>
@tlienart can we close this??

**Comment by tlienart** [comment]
Yes though: @ablaom why is the old interface code still in? shouldn't the ScikitLearn folder be nuked?

**Comment by ablaom** [comment]
Good catch. Yes, this should be nuked. There's no reference to it. Thanks

On 19/06/2020, at 8:37 PM, Thibaut Lienart <notifications@github.com> wrote:


Closed #260 <https://github.com/alan-turing-institute/MLJModels.jl/issues/260>.
