### ISSUE TITLE
Travis failure on linux w LIBSVM

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJModels.jl#28]
https://travis-ci.com/alan-turing-institute/MLJModels.jl/builds/116819858 

Not sure if related to #21. 

Everything fails on Linux yet everything works on Mac which is odd...

**Comment by ablaom** [comment]
The problem appears to be with XGBoost.jl:

<img width="797" alt="Screen Shot 2019-07-17 at 10 14 39 AM" src="https://user-images.githubusercontent.com/30517088/61382968-bf927100-a87b-11e9-9f82-2152972f2bd8.png">

Known issue: https://github.com/dmlc/XGBoost.jl/issues/69
