### ISSUE TITLE
Add PLSRegressor to the model registry

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJModels.jl#312]
cc @filipebraida @azev77 @tlienart

I'm on leave next week. Will try to get this done soon after I return. Thanks for your patience.

**Comment by filipebraida** [comment]
I am updating the README to add more details and example with MLJ. After that, we will release a new version. One question: @tlienart told us to change the name of the package. Do you continue with this?

**Comment by tlienart** [comment]
It's your package so name it as you think is best :) my main point was about discoverability I think but it's up to you.

Great job on pushing this through!

**Comment by ablaom** [comment]
> I am updating the README to add more details and example with MLJ. After that, we will release a new version. One question: @tlienart told us to change the name of the package. Do you continue with this?

Cool. Ping this thread when you're ready.

**Comment by lalvim** [comment]
Hey guys, we are at the end of process.
We changed the package name.

Also, I was updating the README.md with an example, then some questions arised.

I don't want to standardize date before model tuning, because it is not the correct way.
Hence, I realized that I don't know how to standardize data inside a Grid Search.
r1 and r2 can't be found inside the pipeline. Is there any way to do this?

 
```julia
using MLJBase, RDatasets, MLJTuning
@load KPLSRegressor pkg=PartialLeastSquaresRegressor

# loading data and selecting some features
data = dataset("datasets", "longley")[:, 2:5]

# unpacking the target
y, X = unpack(data, ==(:GNP), colname -> true)

# loading the model
regressor = KPLSRegressor()
pls_model = @pipeline Standardizer regressor target=Standardizer

# defining hyperparams for tunning
r1 = range(pls_model, :width, lower=0.001, upper=100.0, scale=:log)
r2 = range(pls_model, :n_factors, lower=1, upper=2)

# attaching tune
self_tuning_pls_model = TunedModel(model =          pls_model,
                                   resampling = CV(nfolds = 10),
                                   tuning = Grid(resolution = 100),
                                   range = [r1,r2],
                                   measure = mae)

# putting into the machine
self_tuning_pls = machine(self_tuning_pls_model, X, y)

# fitting with tunning
fit!(self_tuning_pls, verbosity=0)

# getting the report
report(self_tuning_pls)
```

**Comment by ablaom** [comment]
Yes, this kind of thing is possible by rolling your own composite model. See [here](https://github.com/alan-turing-institute/MLJ.jl/issues/668) for a similar issue. If you're still stuck ping me here or on slack and I work out something.

**Comment by ablaom** [comment]
For my reference: https://github.com/lalvim/PartialLeastSquaresRegressor.jl

**Comment by lalvim** [comment]
@ablaom @tlienart @azev77 
Guys, we're done here. The package is ready and renamed. You can already put it in the registry.

About the previous example that I was talking about pipeline and grid, I decided to leave it out because it would be just an example of use in the readme.

**Comment by ablaom** [comment]
@lalvim Trouble adding to your models to the registry. Are you able to explain this:

```julia
(registry) pkg> add PartialLeastSquaresRegressor
ERROR: The following package names could not be resolved:
 * PartialLeastSquaresRegressor (not found in project, manifest or registry)

julia> using Pkg

julia> Pkg.add(uuid="f4b1acfe-f311-436c-bb79-8483f53c17d5")
ERROR: The following package uuids could not be resolved:
 * f4b1acfe-f311-436c-bb79-8483f53c17d5

Stacktrace:
 [1] pkgerror(::String) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Types.jl:52
 [2] ensure_resolved(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; registry::Bool) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Types.jl:837
 [3] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; preserve::Pkg.Types.PreserveLevel, platform::Pkg.BinaryPlatforms.MacOS, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:178
 [4] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:140
 [5] #add#21 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:67 [inlined]
 [6] add at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:67 [inlined]
 [7] #add#19 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:65 [inlined]
 [8] add at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:65 [inlined]
 [9] add(; name::Nothing, uuid::String, version::Nothing, url::Nothing, rev::Nothing, path::Nothing, mode::Pkg.Types.PackageMode, subdir::Nothing, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:82
 [10] top-level scope at REPL[14]:1
```

**Comment by filipebraida** [comment]
Sorry, @ablaom . 
We did everything we agreed but the register would be missing. I just did it now!

**Comment by ablaom** [comment]
No worries 😄

**Comment by ablaom** [comment]
As new package there is the 3-day stand-down period. Maybe place a [noblock] comment requesting this be waved, in view of the fact it is only a name change and the change is to make it more informative??

**Comment by ablaom** [comment]
https://github.com/JuliaRegistries/General/pull/22871#issuecomment-707493612

**Comment by filipebraida** [comment]
I went to post the comment, and they had already posted it for me. I didn't know that detail. Thank you!

**Comment by ablaom** [comment]
Yeah, that was me :-)

**Comment by filipebraida** [comment]
Ready! Merge was done

**Comment by ablaom** [comment]
No. It's still open:

<img width="1030" alt="Screen Shot 2020-10-16 at 10 48 28 AM" src="https://user-images.githubusercontent.com/30517088/96189595-419ca880-0f9d-11eb-8f96-d718f167ead6.png">

**Comment by filipebraida** [comment]
My email deceived me, and it was another repository that had merge. Sorry.

Now it's gone. :D

**Comment by ablaom** [comment]
@filipebraida I'm sorry but there is a minor issue with PLSRegressor that prevents it being included in the MLJ registry. The `package_name` trait is not set correctly

https://github.com/lalvim/PartialLeastSquaresRegressor.jl/blob/446a1f5982398140329a2f6eb65a0b91a7cb1ca8/src/mlj_interface.jl#L112

The correct entry is `name       = "PartialLeastSquares Regressor"` (no spaces).

**Comment by ablaom** [comment]
Also I see you do not specify a `load_path` for your models (`path = ...` in the `MMI.metadata_model` macros). 

I will make a PR to fix these things for you.

**Comment by ablaom** [comment]
Okay, I've hacked a registry entry. 

In any case, @filipebraida  can you please merge https://github.com/lalvim/PartialLeastSquaresRegressor.jl/pull/16 soon and tag a new release. Otherwise I'll run into issues next time the registry is updated. Thanks.

**Comment by filipebraida** [comment]
Thanks, @ablaom .

I merged lalvim/PartialLeastSquaresRegressor.jl#16 and make a new release.

https://github.com/JuliaRegistries/General/pull/23208
