### ISSUE TITLE
Input type for Sklearn's NB models

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJModels.jl#61]
* [BernoulliNB](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.BernoulliNB.html#sklearn.naive_bayes.BernoulliNB) expects binary input
* [MultinomialNB](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html#sklearn.naive_bayes.MultinomialNB) expects count input though it's mentioned it does also work with fractional (TF-IDF)

Questions: 

- BernoulliNB --> should the `input_scitype` be `MLJBase.Table(MLJBase.Count)`
- atm I've forced the `MLJBase.Table(MLJBase.Count)` for the MultinomialNB as it seems to be made for it, what do you think?

(same question for ComplementNB but it's just a fancy MultinomialNB anyway).

**Comment by ablaom** [comment]
`Count` is for unbounded ordered discrete data, almost always a literal "count". 

BernoulliNB: `MLBase.Table(Binary)` (`Binary` being alias for `Finite{2}`)
MultinomialNB: `MLJBase.Table(MLJBase.Count)`
