### ISSUE TITLE
Make ColorTypes, Distances optional dependencies. 

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJModels.jl#90]
Not sure what uses `ColorTypes`. Maybe it can be dumped altogether.

I think Distances is needed for clustering.jl and maybe nearest_neighbors.jl

**Comment by tlienart** [comment]
I can confirm distances is needed for clustering and nearestneighbors.

ColorTypes can almost certainly be dumped

Re the first 2, what do you suggest? should MLJModels make everything optional? (inc e.g. Distributions and CategoricalArrays?)

**Comment by ablaom** [comment]
With the exception of the packages `ColorTypes, Distances, Parameters` all other MLJModels [deps] are also [deps] of MLJBase (or part of julia Base). So I don't  really see any point in making them optional at this point.

**Comment by tlienart** [comment]
should  we close this then?

**Comment by ablaom** [comment]
resolved by PR #139
