### ISSUE TITLE
pdf smoothing in DecisionTreeClassifier not working properly

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJModels.jl#93]
Smoothing is only being applied across the *support* of the predicted distribution (non-zero values) instead of over all classes.

**Comment by tlienart** [comment]
could you clarify whether it's an  issue with us or with DT.jl ?

**Comment by ablaom** [comment]
Sorry, this is an issue for us, because I introduced a little extra functionality to the classifier (breaking my own policy). Probably pdf smoothing should be an external transformer, but for testing reasons I needed a quick fix to all those `Inf` results coming from cross_entropy. 

I will address this issue.

**Comment by ablaom** [comment]
Okay, in the end I decided the bug is really  a "feature" and updated the documentation. 😄
